### PR TITLE
Add aux input

### PR DESCRIPTION
**Pull request by ste2425**
This PR adds Aux audio support.

It is disabled by default and needs to be enabled.

Two new menu items will be needed for this feature.

| Name | Image | Script |
| -- | -- | -- |
| Use Aux Audio | auxAudio.png | enableAux.sh |
| Configure Aux Audio | auxAudioConfigure.png | configureAux.sh |

On my system i added these menu items under the `Options` sub menu. The changes to the Readme mention these menu items in this location.

It would look something like this:

image

# How does it work?

The VitaDock.conf file has a new configuration item called `Audio_Mode` this defaults to `BT`. If it is set to `AUX` then Bluetooth is powered off and the [Pulse Audio Loopback Module](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-loopback) is loaded.

As the loopback module requires configuration to say which device is its source and sink (input and output) i created a little tool allowing the user to select these devices from a list of devices available on their system. 

The first time Aux is enabled this tool will be automatically run to do the first time configuration. A user can be re-run the tool at any time to modify this configuration. 

The ids of the sink and source devices are stored in the vitadock.conf file so the loopback module can be auto loaded when the RPI reboots.

Clicking the menu items to enable internal or external Bluetooth will disable Aux and re-enable Bluetooth. Both these menu items perform a reboot and it is the actual reboot which will enable Bluetooth. 

# Things of note

* I have added a `.gitattributes` file to default line endings. I initially tried this work on a windows machine which used the wrong line endings. This should ensure all endings are LF regardless of the environment used to write the files.
* I added some default VSCode configuration so its new files always use LF.
* The VitaDock.conf file has been made a key value pair configuration file. However there are limitations to the scripts that update it and read from it.
  * The update script will not create a new config item, the item has to already exist. It can be without a value however
  * Both update and get can be broken if the value equals the config name, consider `MyConfig=MyConfig=10`.
 * The `enableAux` script is run headless from the Menu item. As such for it to run the Aux configuration tool for first time setup i need to spawn a new terminal instance. To do this i use `lxterminal -e /home/pi/configureAux.sh` not 100% sure if this is a good idea hard coding the terminal to use like this. The terminal names seem to change quite often between distros.

# Wiki

I tried to update the wiki to add dev notes on this feature but sadly Github doesn't seem to allow Forking of repositories that power Wiki's.

# Testing

This was developed against the V2 Experimental image. I was unable to build a new image so to test the final changes i deployed a new image. After the first boot copied over all my changes and rebooted. Then i connected the vita and tested that Bluetooth along with Aux worked.

### CODE REVIEW

**Comment by ste2425** [comment]
Just to document, i have noticed a flaw in this implementation.

When turning off Bluetooth (idea being to save resources) if the command is run when no Bluetooth adapter is available on the RPI the command will hang.

I expected it to write to stderr then the script continue.

I will look into making that smarter so that if the RPI does have Bluetooth hardware (either built in or via a dongle) we run the command, otherwise skip it.

Also need to update the documentation in the Readme to include info on specific extra hardware used (USB line in and ground loop isolator)

**Comment by novamax89** [comment]
Hello. 
I would like to try your pull request as I want to use the aux audio output from the official PlayStation dock. 
Will it work with the raspiaudio mic+v2 that is possible to find on Amazon?
Is it possible to build an image including your pull request, and if in not asking much, how could I build it?
Many thanks anyway I think your work will make vitadock+ perfect.

**Comment by ste2425** [comment]
@novamax89 

* `raspiaudio mic+v2` : I'm afraid i do not now. I have not used this device but used two external USB sound cards. Any device which appears to Pulse Audio as a source should work. However i cannot guarantee every device will as i haven't tested every device!

* `Building an Image`: SilentNightx is working hard on building a new image with these changes in.

However you can, if confident, manually edit the scripts on your deployed dock. However that would only be advised for advanced users. Its not a expected use case so i wouldn't be able to offer step by step guidance on how, never mind any thing that may break as a result.

* `Building your own`: I don't know if you mean your own image or setting up the PSVita for Aux. If you mean setting up for Aux the needed equipment and process can be read in the changes to the ReadMe as part of this PR.

**Comment by novamax89** [comment]
Many thanks. I ordered raspiaudio and I will try to edit the scripts and will let you know

**Comment by novamax89** [comment]
I copied your files over to the v2 experimental but can’t get it working. The sound icon is no longer showing and I still can’t see the 2 aux options in the option menu. Maybe I’m doing something wrong but always good to report. Done on Rpi3b

**Comment by ste2425** [comment]
@novamax89 I'm going to do a little write up on my blog about manually applying these changes. Mostly so i don't forget how.

I don't think this Github issue is the best place for support of manually applying the changes. Don't want to speak for the maintainers but i don't think manually applying changes is anexpected use case.

I don't want to cause more work for the maintainers dealing with notifications and support requests around such issues.

Hopefully my write up will give you all the needed info to do this yourself. Ill ping back once its written.

**Comment by novamax89** [comment]
Hello do you have any update? Thanks

**Comment by ste2425** [comment]
@novamax89  Sorry for the delay, real life got in the way.

There's probably tons of typos but it should hopefully get you going.

[Apply Aux Audio Manually](https://ste2425.github.io/12/05/2023/VitaDock-Manually-Apply-Aux-Audio-Feature/)

**Comment by novamax89** [comment]
> @novamax89 Sorry for the delay, real life got in the way.
> 
> There's probably tons of typos but it should hopefully get you going.
> 
> [Apply Aux Audio Manually](https://ste2425.github.io/12/05/2023/VitaDock-Manually-Apply-Aux-Audio-Feature/)

Thanks!  I couldn’t get mine to work, probably due to the installation of raspiaudio card that doesn’t work unfortunately

**Comment by novamax89** [comment]
What usb card did you use? I’ll return the raspiaudio to Amazon

**Comment by ste2425** [comment]
@novamax89  I used a cheap generic USB audio card and a Playtonics headset i got from work.

The Headset i opened up the PCB, se-soldered the speakers and soldered a AUX cable in place of the mic. Sadly i don't know the exact model so don't have a link.

The sound card was [this](https://www.ebay.co.uk/itm/255659290779?var=555595492265) one. However its so cheap and generic i can't guarantee you would receive the exact same thing i got.

In both scenarios they are mono inputs so you need a stereo to mono adapter for the aux cable.

Iv'e had both connected and toggled between them using the `Aux Configuration Tool` and they sound the same with no difference in lag.

**Pull request merged**
